In [5]:
import pandas as pd
import numpy as np

In [22]:
temp = pd.read_csv("data/tracts_data_v1.csv")

In [23]:
temp

,population_density,housing_density,median_age,median_male_age,pct_white,median_income,school_districts,pct_lt_hs_grad,median_rooms,pct_hs_grad,pct_at_least_col_grad,GEOID,state,tract,NAME,NatWalkInd,ALAND,ALAND_SQMI,county
0,79.338110,29.598926,39.8,39.2,0.944755,66217,"['Calhoun County School District', 'Jacksonvil...",0.075424,6.0,0.342623,0.210290,1015002000,1,2000,"Census Tract 20, Calhoun County, Alabama",3.066667,239320450,92.402,15
1,704.235463,303.661163,41.7,39.2,0.427115,27656,['Anniston City School District'],0.271277,5.1,0.369681,0.103723,1015000800,1,800,"Census Tract 8, Calhoun County, Alabama",11.500000,3607490,1.393,15
2,773.193673,326.635314,44.3,40.9,0.684545,50810,"['Anniston City School District', 'Calhoun Cou...",0.101916,6.4,0.244444,0.347510,1015000900,1,900,"Census Tract 9, Calhoun County, Alabama",5.166667,12114697,4.678,15
3,381.262279,144.646365,47.1,43.7,0.805797,42083,['Calhoun County School District'],0.263764,5.7,0.393513,0.042680,1015001400,1,1400,"Census Tract 14, Calhoun County, Alabama",5.291667,21093280,8.144,15
4,417.341473,163.448362,34.8,39.4,0.768955,69875,"['Calhoun County School District', 'Jacksonvil...",0.034483,6.5,0.164655,0.495690,1015002102,1,2102,"Census Tract 21.02, Calhoun County, Alabama",7.166667,20789534,8.027,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54445,1618.459003,752.781211,44.2,41.6,0.932026,47156,['Oshkosh Area School District'],0.081006,5.4,0.430866,0.156774,55139001400,55,1400,"Census Tract 14, Winnebago County, Wisconsin",12.583333,6286797,2.427,139
54446,3048.312376,1203.838518,35.2,34.5,0.849544,47628,['Neenah School District'],0.070639,5.2,0.427519,0.187814,55139003400,55,3400,"Census Tract 34, Winnebago County, Wisconsin",11.625000,3913783,1.511,139
54447,4030.710173,1909.788868,43.4,37.0,0.877857,35446,['Oshkosh Area School District'],0.056426,4.7,0.397074,0.212818,55139001100,55,1100,"Census Tract 11, Winnebago County, Wisconsin",14.666667,2698989,1.042,139
54448,102.212811,41.015875,42.4,41.8,0.985957,68457,"['Omro School District', 'Oshkosh Area School ...",0.044816,6.0,0.349358,0.288857,55139002000,55,2000,"Census Tract 20, Winnebago County, Wisconsin",6.100000,182238158,70.363,139
54449,43.087771,17.270810,46.6,46.2,0.983169,66103,"['Berlin Area School District', 'Omro School D...",0.106465,6.0,0.386859,0.185875,55139002100,55,2100,"Census Tract 21, Winnebago County, Wisconsin",3.416667,232142673,89.631,139

In [25]:
#Clean up some of the rows that contian missing values
# -666666666 is missing and should remove this row
df = temp.copy()
for col in temp.columns:
    df = df.loc[df[col]!=-666666666]

In [26]:
df.columns

Index(['population_density', 'housing_density', 'median_age',
       'median_male_age', 'pct_white', 'median_income', 'school_districts',
       'pct_lt_hs_grad', 'median_rooms', 'pct_hs_grad',
       'pct_at_least_col_grad', 'GEOID', 'state', 'tract', 'NAME',
       'NatWalkInd', 'ALAND', 'ALAND_SQMI', 'county'],
      dtype='object')

In [27]:
#Let's look for county pairings
states = np.unique(df.state)
states

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  86,  87,  89,  91,  93,  95,  97,  99, 101,
       103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127,
       129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153,
       155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 197, 201, 209, 215, 217, 223, 227,
       245, 251, 257, 303, 309, 313, 329, 339, 355, 367, 375, 381, 397,
       423, 439, 441, 451, 453, 479, 485, 491])

In [68]:
#Set a list of eval_columns to use for evaluation
eval_columns = ['population_density', 'housing_density', 'median_age',
       'median_male_age', 'median_income', 'pct_hs_grad', 'NatWalkInd']

In [73]:
#Closeness calculation
def calculation(column_name):
    return (np.max(df[column_name])-np.min(df[column_name]))*.01

In [74]:
#Use a dictionary to store the std dev & mean for each column
eval_dict = {}

for col in eval_columns:
    eval_dict[col] = calculation(col)
    
eval_dict

{'population_density': 2505.962939682903,
 'housing_density': 1636.6659339874846,
 'median_age': 0.7689999999999999,
 'median_male_age': 0.799,
 'median_income': 2475.02,
 'median_rooms': 0.087,
 'pct_hs_grad': 0.0071428571428571435,
 'NatWalkInd': 0.1883333333}

In [80]:
pairings = [] #List of tuples to store GEOIDS of possible pairings

for state in states[2:]:
    temp = df.loc[df['state']==state]
    counties = np.unique(temp.county)
    
    for county in counties:
        temp2 = temp.loc[temp['county']==county]
        
        #Find the unique tracts in this county & state
        ids = np.unique(temp2.GEOID)
    
        #Some optimization since I don't need to double check pairs that have already been tried
        for i in range(len(ids)-1):
            a = ids[i]
            for j in range(i+1, len(ids)-1):
                b = ids[j]
                
                #First need to confirm geoids are racially different
                if ((temp2.loc[temp2['GEOID']==a, "pct_white"].item() < .5)
                and (temp2.loc[temp2['GEOID']==b, "pct_white"].item() > .5)) or ((temp2.loc[temp2['GEOID']==a, "pct_white"].item() > .5)
                and (temp2.loc[temp2['GEOID']==b, "pct_white"].item() < .5)):
     

                    #a and b are two geoids which can be used to find a tract
                    #Here is a potential comparison we can use to find pairs
                    for col in eval_columns:
                        #print(temp2.loc[temp2['GEOID']==a, col].item())
                        if abs(temp2.loc[temp2['GEOID']==a, col].item()-temp2.loc[temp2['GEOID']==b, col].item()) <= eval_dict[col]:
                            continue
                        else:
                            break
                    else:
                        pairings.append((a,b))

In [81]:
len(pairings)

0