In [2]:
import pandas as pd
import numpy as np

In [3]:
temp = pd.read_csv("data/tracts_data_hisp.csv")

In [4]:
temp

,population_density,housing_density,median_age,median_male_age,pct_white,median_income,school_districts,pct_lt_hs_grad,median_rooms,pct_hs_grad,...,GEOID,state,tract,NAME,NatWalkInd,ALAND,ALAND_SQMI,county,pct_black,pct_hisp
0,79.338110,29.598926,39.8,39.2,0.928386,66217,"['Calhoun County School District', 'Jacksonvil...",0.075424,6.0,0.342623,...,1015002000,1,2000,"Census Tract 20, Calhoun County, Alabama",3.066667,239320450,92.402,15,0.032601,0.016369
1,704.235463,303.661163,41.7,39.2,0.426096,27656,['Anniston City School District'],0.271277,5.1,0.369681,...,1015000800,1,800,"Census Tract 8, Calhoun County, Alabama",11.500000,3607490,1.393,15,0.542304,0.001019
2,773.193673,326.635314,44.3,40.9,0.681228,50810,"['Anniston City School District', 'Calhoun Cou...",0.101916,6.4,0.244444,...,1015000900,1,900,"Census Tract 9, Calhoun County, Alabama",5.166667,12114697,4.678,15,0.278684,0.006635
3,381.262279,144.646365,47.1,43.7,0.798712,42083,['Calhoun County School District'],0.263764,5.7,0.393513,...,1015001400,1,1400,"Census Tract 14, Calhoun County, Alabama",5.291667,21093280,8.144,15,0.184863,0.016425
4,417.341473,163.448362,34.8,39.4,0.765075,69875,"['Calhoun County School District', 'Jacksonvil...",0.034483,6.5,0.164655,...,1015002102,1,2102,"Census Tract 21.02, Calhoun County, Alabama",7.166667,20789534,8.027,15,0.179403,0.011940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54445,1618.459003,752.781211,44.2,41.6,0.911660,47156,['Oshkosh Area School District'],0.081006,5.4,0.430866,...,55139001400,55,1400,"Census Tract 14, Winnebago County, Wisconsin",12.583333,6286797,2.427,139,0.041242,0.025458
54446,3048.312376,1203.838518,35.2,34.5,0.838254,47628,['Neenah School District'],0.070639,5.2,0.427519,...,55139003400,55,3400,"Census Tract 34, Winnebago County, Wisconsin",11.625000,3913783,1.511,139,0.086192,0.051238
54447,4030.710173,1909.788868,43.4,37.0,0.860476,35446,['Oshkosh Area School District'],0.056426,4.7,0.397074,...,55139001100,55,1100,"Census Tract 11, Winnebago County, Wisconsin",14.666667,2698989,1.042,139,0.014762,0.017381
54448,102.212811,41.015875,42.4,41.8,0.957036,68457,"['Omro School District', 'Oshkosh Area School ...",0.044816,6.0,0.349358,...,55139002000,55,2000,"Census Tract 20, Winnebago County, Wisconsin",6.100000,182238158,70.363,139,0.000000,0.029755
54449,43.087771,17.270810,46.6,46.2,0.911704,66103,"['Berlin Area School District', 'Omro School D...",0.106465,6.0,0.386859,...,55139002100,55,2100,"Census Tract 21, Winnebago County, Wisconsin",3.416667,232142673,89.631,139,0.001813,0.071466

In [5]:
#Clean up some of the rows that contian missing values
# -666666666 is missing and should remove this row
df = temp.copy()
for col in temp.columns:
    df = df.loc[df[col]!=-666666666]

In [6]:
df.columns

Index(['population_density', 'housing_density', 'median_age',
       'median_male_age', 'pct_white', 'median_income', 'school_districts',
       'pct_lt_hs_grad', 'median_rooms', 'pct_hs_grad',
       'pct_at_least_col_grad', 'GEOID', 'state', 'tract', 'NAME',
       'NatWalkInd', 'ALAND', 'ALAND_SQMI', 'county', 'pct_black', 'pct_hisp'],
      dtype='object')

In [7]:
#Let's look for county pairings
states = np.unique(df.state)
states

array([ 1,  4,  5,  6,  8,  9, 10, 12, 13, 15, 16, 17, 18, 19, 20, 21, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55])

In [8]:
#Set a list of eval_columns to use for evaluation
eval_columns = ['population_density', 'housing_density', 'median_age',
       'median_male_age', 'median_income',  'pct_hs_grad', 'NatWalkInd']

In [9]:
#Closeness calculation
f = .0175 #Resulted in 0 when .01 #resulted in 200,558 when .1
def calculation(column_name):
    #return (np.max(df[column_name])-np.min(df[column_name]))*f
    return np.std(df[column_name])*.125

In [10]:
#Use a dictionary to store the std dev & mean for each column
eval_dict = {}

for col in eval_columns:
    eval_dict[col] = calculation(col)
    
eval_dict

{'population_density': 1674.5671124173377,
 'housing_density': 694.4850574695918,
 'median_age': 0.9866095683208753,
 'median_male_age': 1.0028791377358233,
 'median_income': 4478.9103914111,
 'pct_hs_grad': 0.013345924814694678,
 'NatWalkInd': 0.4703934725453669}

In [11]:
#Use a dictionary to store the std dev & mean for each column
eval_dict = {}

for col in eval_columns:
    eval_dict[col] = calculation(col)
    
eval_dict

{'population_density': 1674.5671124173377,
 'housing_density': 694.4850574695918,
 'median_age': 0.9866095683208753,
 'median_male_age': 1.0028791377358233,
 'median_income': 4478.9103914111,
 'pct_hs_grad': 0.013345924814694678,
 'NatWalkInd': 0.4703934725453669}

In [ ]:
pairings = [] #List of tuples to store GEOIDS of possible pairings

for state in states[2:]:
    temp = df.loc[df['state']==state]
    counties = np.unique(temp.county)
    
    for county in counties:
        temp2 = temp.loc[temp['county']==county]
        
        #Find the unique tracts in this county & state
        ids = np.unique(temp2.GEOID)
    
        #Some optimization since I don't need to double check pairs that have already been tried
        for i in range(len(ids)-1):
            a = ids[i]
            for j in range(i+1, len(ids)-1):
                b = ids[j]
                
                #First need to confirm geoids are racially different
                if ((temp2.loc[temp2['GEOID']==a, "pct_white"].item() < .5)
                and (temp2.loc[temp2['GEOID']==b, "pct_white"].item() > .5)) or ((temp2.loc[temp2['GEOID']==a, "pct_white"].item() > .5)
                and (temp2.loc[temp2['GEOID']==b, "pct_white"].item() < .5)):
     

                    #a and b are two geoids which can be used to find a tract
                    #Here is a potential comparison we can use to find pairs
                    for col in eval_columns:
                        #print(temp2.loc[temp2['GEOID']==a, col].item())
                        if abs(temp2.loc[temp2['GEOID']==a, col].item()-temp2.loc[temp2['GEOID']==b, col].item()) <= eval_dict[col]:
                            continue
                        else:
                            break
                    else:
                        pairings.append((a,b))

In [ ]:
len(pairings)

In [152]:
print(pairings)

[(6037104320, 6037127210), (6037124204, 6037195720), (6037228310, 6037531502), (6037310800, 6037482002), (6037402903, 6037541100), (6037405800, 6037541200), (6037407601, 6037540102), (6037432802, 6037533603), (6037434001, 6037500402), (6037550800, 6037570100), (6059001707, 6059032038), (6059099408, 6059110102), (6065041408, 6065042517), (6095252501, 6095253107), (12011010200, 12011060105), (12031010304, 12031016722), (13121011618, 13121011623), (17031822702, 17031840200), (18097320204, 18097350100), (25013801901, 25013811600), (42045402800, 42045403002), (48113010804, 48113010902), (48201220400, 48201532200), (48201220900, 48201520601), (48201433202, 48201453401), (48439111541, 48439121611)]

In [153]:
newdf = pd.DataFrame()
paircount = 0
for pair in pairings:
    for geoid in pair:
        newdf = newdf.append(df.loc[df['GEOID']==geoid])
        newdf.loc[newdf['GEOID']==geoid, "Pair_ID"] = paircount
    paircount+=1

In [154]:
newdf.to_csv("pairings_26.csv")

In [2]:
#Code to add the lat & long
pairs = pd.read_csv("pairings_26.csv")

In [7]:
land_area = pd.read_csv("data/2019_Gaz_tracts_national.txt", sep="\t")
land_area.columns

Index(['USPS', 'GEOID', 'ALAND', 'AWATER', 'ALAND_SQMI', 'AWATER_SQMI',
       'INTPTLAT',
       'INTPTLONG                                                                                                                             '],
      dtype='object')

In [8]:
land_area.columns = ['USPS', 'GEOID', 'ALAND', 'AWATER', 'ALAND_SQMI', 'AWATER_SQMI','INTPTLAT','INTPTLONG']
land_area.columns

Index(['USPS', 'GEOID', 'ALAND', 'AWATER', 'ALAND_SQMI', 'AWATER_SQMI',
       'INTPTLAT', 'INTPTLONG'],
      dtype='object')

In [9]:
tracts = pairs.merge(land_area[["GEOID",'INTPTLAT','INTPTLONG']], how = "left", on = "GEOID")
tracts

,Unnamed: 0,population_density,housing_density,median_age,median_male_age,pct_white,median_income,school_districts,pct_lt_hs_grad,median_rooms,...,state,tract,NAME,NatWalkInd,ALAND,ALAND_SQMI,county,Pair_ID,INTPTLAT,INTPTLONG
0,5189,11307.692308,2844.017094,34.3,33.0,0.654573,56021,['Los Angeles Unified School District'],0.462554,4.6,...,6,104320,"Census Tract 1043.20, Los Angeles County, Cali...",15.208333,1212169,0.468,37,0.0,34.273132,-118.420249
1,3512,9828.282828,3207.070707,33.8,33.1,0.372559,55997,['Los Angeles Unified School District'],0.223566,3.5,...,6,127210,"Census Tract 1272.10, Los Angeles County, Cali...",15.055556,1539742,0.594,37,0.0,34.206637,-118.459647
2,5106,17536.000000,7432.000000,40.2,41.5,0.712135,43385,['Los Angeles Unified School District'],0.297126,2.9,...,6,124204,"Census Tract 1242.04, Los Angeles County, Cali...",15.000000,324351,0.125,37,1.0,34.173972,-118.374655
3,5615,17857.142857,7660.714286,39.5,41.2,0.380000,41136,['Los Angeles Unified School District'],0.333544,3.2,...,6,195720,"Census Tract 1957.20, Los Angeles County, Cali...",15.083333,288980,0.112,37,1.0,34.073757,-118.263377
4,4081,21436.018957,4947.867299,28.4,27.2,0.440637,44375,['Los Angeles Unified School District'],0.626651,4.3,...,6,228310,"Census Tract 2283.10, Los Angeles County, Cali...",14.875000,546319,0.211,37,2.0,34.011351,-118.262416
5,5145,20220.238095,4803.571429,28.7,26.8,0.594054,45404,"['Los Angeles Unified School District', 'Monte...",0.589332,4.8,...,6,531502,"Census Tract 5315.02, Los Angeles County, Cali...",14.833333,435565,0.168,37,2.0,34.019891,-118.170847
6,5492,6441.212121,2397.575758,39.6,39.2,0.730523,66429,['Burbank Unified School District'],0.075026,4.5,...,6,310800,"Census Tract 3108, Los Angeles County, California",15.366667,2136454,0.825,37,3.0,34.174149,-118.322183
7,3831,7034.339230,2601.456816,40.3,39.3,0.097633,66103,"['Alhambra Unified School District', 'Montebel...",0.137069,4.6,...,6,482002,"Census Tract 4820.02, Los Angeles County, Cali...",15.833333,2488396,0.961,37,3.0,34.048837,-118.148268
8,3699,7082.792208,1594.155844,30.9,30.2,0.508366,56667,['Pomona Unified School District'],0.330922,5.4,...,6,402903,"Census Tract 4029.03, Los Angeles County, Cali...",13.333333,1594430,0.616,37,4.0,34.039394,-117.733543
9,4160,6772.916667,1912.500000,31.7,30.4,0.275300,59375,"['Compton Unified School District', 'Los Angel...",0.285300,5.3,...,6,541100,"Census Tract 5411, Los Angeles County, California",13.777778,1244459,0.480,37,4.0,33.898470,-118.260751
10,5532,7957.650273,2241.803279,34.9,32.8,0.560858,79728,"['Azusa Unified School District', 'Covina-Vall...",0.213965,5.0,...,6,405800,"Census Tract 4058, Los Angeles County, California",14.500000,1895340,0.732,37,5.0,34.103394,-117.912680
11,5280,7982.926829,2259.756098,35.6,32.2,0.220745,82125,['Compton Unified School District'],0.192289,5.5,...,6,541200,"Census Tract 5412, Los Angeles County, California",14.133333,2123398,0.820,37,5.0,33.907644,-118.254386
12,4028,15258.278146,3695.364238,30.8,30.9,0.297092,61429,['Hacienda La Puente Unified School District'],0.390076,4.7,...,6,407601,"Census Tract 4076.01, Los Angeles County, Cali...",14.611111,781203,0.302,37,6.0,34.038410,-117.946173
13,4556,14296.066253,3233.954451,30.7,30.5,0.570456,60934,['Lynwood Unified School District'],0.351681,5.3,...,6,540102,"Census Tract 5401.02, Los Angeles County, Cali...",14.708333,1250584,0.483,37,6.0,33.923195,-118.194185
14,5665,22267.543860,6122.807018,28.6,28.6,0.467993,39474,"['El Monte City School District', 'El Monte Un...",0.444850,3.9,...,6,432802,"Census Tract 4328.02, Los Angeles County, Cali...",12.666667,591782,0.228,37,7.0,34.078861,-118.053301
15,5777,22391.025641,5714.743590,29.4,27.6,0.777269,42750,['Los Angeles Unified School District'],0.426052,4.1,...,6,533603,"Census Tract 5336.03, Los Angeles County, Cali...",12.444444,806971,0.312,37,7.0,33.972473,-118.195066
16,4373,10327.868852,2309.133489,31.2,31.3,0.506122,52436,"['El Monte Union High School District', 'Mount...",0.423949,5.0,...,6,434001,"Census Tract 4340.01, Los Angeles County, Cali...",15.500000,1105066,0.427,37,8.0,34.052077,-118.014117
17,5550,9410.852713,2306.201550,31.0,30.7,0.342257,54375,['El Rancho Unified School District'],0.382275,4.4,...,6,500402,"Census Tract 5004.02, Los Angeles County, Cali...",15.388889,1335853,0.516,37,8.0,34.003602,-118.076382
18,4151,6705.615942,1881.340580,38.2,38.2,0.714440,82479,"['Downey Unified School District', 'Los Angele...",0.214088,5.4,...,6,550800,"Census Tract 5508, Los Angeles County, California",13.595238,2860226,1.104,37,9.0,33.951270,-118.143356
19,4270,7156.950673,1690.582960,38.5,39.1,0.381579,79750,"['Long Beach Unified School District', 'Paramo...",0.212389,5.5,...,6,570100,"Census Tract 5701, Los Angeles County, California",14.000000,1154366,0.446,37,9.0,33.864463,-118.153221
20,6325,3665.661136,1261.437908,45.4,46.2,0.226992,133993,"['Buena Park Elementary School District', 'Ful...",0.031055,6.4,...,6,1707,"Census Tract 17.07, Orange County, California",11.625000,5152163,1.989,59,10.0,33.904692,-117.968161
21,6441,4663.489736,1537.390029,45.6,45.3,0.748939,137266,"['Capistrano Unified School District', 'Saddle...",0.038352,7.2,...,6,32038,"Census Tract 320.38, Orange County, California",11.166667,3532420,1.364,59,10.0,33.594117,-117.645041
22,6327,8937.743191,3256.809339,43.2,43.3,0.752503,108478,['Huntington Beach Union High School District'...,0.053111,5.7,...,6,99408,"Census Tract 994.08, Orange County, California",14.055556,1331052,0.514,59,11.0,33.722607,-118.037174
23,6347,9838.435374,3042.517007,42.9,42.8,0.370614,111169,"['Anaheim Union High School District', 'Centra...",0.084915,6.1,...,6,110102,"Census Tract 1101.02, Orange County, California",14.333333,1522630,0.588,59,11.0,33.841660,-118.045002
24,7030,8344.262295,2402.550091,29.6,28.4,0.521720,55993,"['Alvord Unified School District', 'Riverside ...",0.247270,4.0,...,6,41408,"Census Tract 414.08, Riverside County, California",11.916667,1422469,0.549,65,12.0,33.904209,-117.469161
25,7187,9162.087912,2222.527473,30.1,28.0,0.398501,56130,['Moreno Valley Unified School District'],0.320688,5.4,...,6,42517,"Census Tract 425.17, Riverside County, California",11.750000,943427,0.364,65,12.0,33.911923,-117.213172
26,9720,6473.563218,2142.528736,32.1,29.8,0.456676,49677,['Fairfield-Suisun Unified School District'],0.168802,4.6,...,6,252501,"Census Tract 2525.01, Solano County, California",14.916667,1126761,0.435,95,13.0,38.254704,-122.041278
27,9727,6253.564155,2354.378819,31.2,29.2,0.684253,53685,['Vacaville Unified School District'],0.074125,5.1,...,6,253107,"Census Tract 2531.07, Solano County, California",15.041667,2543548,0.982,95,13.0,38.342090,-121.979051
28,12819,6119.318182,2320.075758,43.9,44.6,0.793253,48442,['Broward County School District'],0.139917,4.3,...,12,10200,"Census Tract 102, Broward County, Florida",13.888889,2734652,1.056,11,14.0,26.311098,-80.097874
29,12696,6961.776860,2882.231405,43.9,44.5,0.447396,46297,['Broward County School District'],0.111782,4.6,...,12,60105,"Census Tract 601.05, Broward County, Florida",13.750000,2506485,0.968,11,14.0,26.198792,-80.241183
30,13156,2106.103024,766.797312,36.9,35.4,0.096371,55744,['Duval County School District'],0.042333,5.5,...,12,10304,"Census Tract 103.04, Duval County, Florida",10.777778,9252095,3.572,31,15.0,30.442820,-81.656155
31,13093,3121.942040,1247.271359,37.0,35.5,0.706088,53307,['Duval County School District'],0.096660,5.2,...,12,16722,"Census Tract 167.22, Duval County, Florida",11.055556,6881790,2.657,31,15.0,30.195021,-81.603842
32,17059,2300.650325,801.400700,43.3,43.1,0.564253,122857,['Fulton County School District'],0.029223,7.8,...,13,11618,"Census Tract 116.18, Fulton County, Georgia",8.166667,5178115,1.999,121,16.0,34.056505,-84.264963
33,17064,3553.946621,1240.772288,42.8,42.4,0.470240,121389,['Fulton County School District'],0.043056,7.1,...,13,11623,"Census Tract 116.23, Fulton County, Georgia",8.333333,9120721,3.522,121,16.0,34.022421,-84.180364
34,18349,7333.333333,2892.215569,39.3,37.4,0.841045,61342,"['Community High School District 218', 'Oak La...",0.096110,5.4,...,17,822702,"Census Tract 8227.02, Cook County, Illinois",16.777778,1298804,0.501,31,17.0,41.705691,-87.730580
35,18700,7583.072100,2605.015674,38.9,37.3,0.300951,61806,['Chicago Public School District 299'],0.296629,5.3,...,17,840200,"Census Tract 8402, Cook County, Illinois",17.166667,826355,0.319,31,17.0,41.844648,-87.649210
36,21127,2223.032630,1034.932821,34.7,30.4,0.604041,41504,['Washington Township Metropolitan School Dist...,0.100416,3.8,...,18,320204,"Census Tract 3202.04, Marion County, Indiana",13.111111,6747572,2.605,97,18.0,39.918413,-86.109204
37,21134,1942.812983,799.072643,35.0,31.0,0.140016,38750,['Indianapolis Public Schools'],0.158439,5.5,...,18,350100,"Census Tract 3501, Marion County, Indiana",12.666667,1676841,0.647,97,18.0,39.811912,-86.190834
38,24272,11808.917197,4073.248408,25.4,22.2,0.359493,21596,['Springfield School District'],0.337228,4.3,...,25,801901,"Census Tract 8019.01, Hampden County, Massachu...",14.583333,812271,0.314,13,19.0,42.095098,-72.571419
39,24308,12707.395498,4003.215434,25.3,22.1,0.826164,22807,['Holyoke School District'],0.402820,4.4,...,25,811600,"Census Tract 8116, Hampden County, Massachusetts",14.708333,804837,0.311,13,19.0,42.201221,-72.613967
40,43202,7362.694301,2670.984456,35.8,36.4,0.212526,57206,['Southeast Delco School District'],0.077597,6.2,...,42,402800,"Census Tract 4028, Delaware County, Pennsylvania",15.600000,1998625,0.772,45,20.0,39.907433,-75.267787
41,43312,7005.263158,2976.315789,36.7,36.1,0.730278,53262,['Southeast Delco School District'],0.076489,6.0,...,42,403002,"Census Tract 4030.02, Delaware County, Pennsyl...",15.500000,983090,0.380,45,20.0,39.911533,-75.292939
42,47642,7397.419355,2358.709677,27.2,23.9,0.563928,37566,['Dallas Independent School District'],0.442175,4.3,...,48,10804,"Census Tract 108.04, Dallas County, Texas",13.083333,2007940,0.775,113,21.0,32.713264,-96.862679
43,48125,6458.039216,2386.666667,27.2,24.5,0.170877,33210,"['Dallas Independent School District', 'Duncan...",0.181036,4.3,...,48,10902,"Census Tract 109.02, Dallas County, Texas",12.833333,3302064,1.275,113,21.0,32.658437,-96.863814
44,48820,5778.532609,1721.467391,33.4,33.9,0.870680,36530,['Houston Independent School District'],0.518882,5.2,...,48,220400,"Census Tract 2204, Harris County, Texas",12.722222,1905169,0.736,201,22.0,29.831578,-95.366322
45,49441,5408.077994,1909.470752,32.7,33.7,0.471285,38972,"['Aldine Independent School District', 'Housto...",0.504129,4.3,...,48,532200,"Census Tract 5322, Harris County, Texas",12.833333,1860154,0.718,201,22.0,29.856994,-95.484421
46,49400,3036.332180,851.211073,29.3,29.7,0.802279,39891,"['Aldine Independent School District', 'Housto...",0.417085,5.1,...,48,220900,"Census Tract 2209, Harris County, Texas",14.333333,1497348,0.578,201,23.0,29.848841,-95.337638
47,48812,3591.567852,1063.241107,29.2,30.5,0.312179,36250,['Cypress-Fairbanks Independent School Distric...,0.375387,4.1,...,48,520601,"Census Tract 5206.01, Harris County, Texas",14.666667,1964841,0.759,201,23.0,29.816796,-95.492676
48,49236,9614.864865,2918.918919,30.6,30.9,0.334505,46677,['Houston Independent School District'],0.259417,5.3,...,48,433202,"Census Tract 4332.02, Harris County, Texas",12.500000,1150085,0.444,201,24.0,29.696804,-95.541248
49,48831,8540.760870,2766.304348,31.4,31.2,0.583201,44500,['Alief Independent School District'],0.241249,4.8,...,48,453401,"Census Tract 4534.01, Harris County, Texas",12.916667,953326,0.368,201,24.0,29.654511,-95.576314
50,50378,5292.984869,1796.423659,33.6,34.1,0.443347,69138,"['Arlington Independent School District', 'Man...",0.089113,5.6,...,48,111541,"Census Tract 1115.41, Tarrant County, Texas",8.000000,1883536,0.727,439,25.0,32.651782,-97.108563
51,50298,4421.551724,1378.448276,34.5,34.7,0.705206,72361,"['Arlington Independent School District', 'Ken...",0.060624,6.0,...,48,121611,"Census Tract 1216.11, Tarrant County, Texas",7.541667,3003370,1.160,439,25.0,32.675881,-97.211019

In [11]:
tracts.to_csv("pairs_with_latlong.csv", index=False)